### ISSUE TITLE
Error when using custom location for volumes

### ISSUE THREAD

**Issue by diethardsteiner** [HiromuHota/webspoon-docker#1]
I'd like to be able to specify I custom location for the volumes. Currently when I run this:

```
docker run -e JAVA_OPTS="-Xms1024m -Xmx2048m" -d -p 8080:8080 -v /home/dsteiner/webspoon/kettle:/root/.kettle -v /home/dsteiner/webspoon/pentaho:/root/.pentaho hiromuhota/webspoon:latest-full
```

I get following error:

```
25-Dec-2017 20:58:25.511 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
25-Dec-2017 20:59:40.970 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Spoon] in context with path [/spoon] threw exception
 java.lang.RuntimeException: Central Log Store is not initialized!!!
at org.pentaho.di.core.logging.KettleLogStore.getInstance(KettleLogStore.java:185)
at org.pentaho.di.core.logging.KettleLogStore.getAppender(KettleLogStore.java:235)
at org.pentaho.di.core.logging.LogChannel.println(LogChannel.java:123)
at org.pentaho.di.core.logging.LogChannel.println(LogChannel.java:134)
at org.pentaho.di.core.logging.LogChannel.logError(LogChannel.java:158)
at org.pentaho.di.ui.spoon.Spoon.<init>(Spoon.java:784)
at org.pentaho.di.ui.spoon.Spoon.<init>(Spoon.java:762)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.eclipse.rap.rwt.internal.util.ClassUtil.createInstance(ClassUtil.java:57)
at org.eclipse.rap.rwt.internal.util.ClassUtil.newInstance(ClassUtil.java:38)
at org.eclipse.rap.rwt.internal.util.ClassUtil.newInstance(ClassUtil.java:32)
at org.eclipse.rap.rwt.internal.SingletonManager.getSingleton(SingletonManager.java:46)
at org.eclipse.rap.rwt.SingletonUtil.getUniqueInstance(SingletonUtil.java:74)
at org.eclipse.rap.rwt.SingletonUtil.getSessionInstance(SingletonUtil.java:58)
at org.pentaho.di.ui.spoon.Spoon.getInstance(Spoon.java:1084)
at org.pentaho.di.ui.spoon.WebSpoonEntryPoint.createContents(WebSpoonEntryPoint.java:72)
at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:60)
at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
at java.lang.Thread.run(Thread.java:748)
at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
```

**Comment by HiromuHota** [comment]
Thank you for reporting, but I need more information to find out what was wrong.
I'm assuming it depends on the Docker environment and not on the Docker image (including webSpoon war file).
Please tell me your OS and Docker version.

As far as I tested, I was not able to reproduce the error.
### Environment 1
OS: Ubuntu 16.04.3 LTS
Docker: version 17.09.1-ce, build 19e2cf6

```
$ mkdir kettle
$ mkdir pentaho
$ sudo docker run -e JAVA_OPTS="-Xms1024m -Xmx2048m" -d -p 8080:8080 -v /home/ubuntu/kettle:/root/.kettle -v /home/ubuntu/pentaho:/root/.pentaho hiromuhota/webspoon:latest-full
```

### Environment 2
OS: centos-release-7-4.1708.el7.centos.x86_64 (SELinux: enforcing)
Docker: version 17.09.1-ce, build 19e2cf6

```
$ mkdir kettle
$ mkdir pentaho
$ sudo docker run -e JAVA_OPTS="-Xms1024m -Xmx2048m" -d -p 8080:8080 -v /home/vagrant/kettle:/root/.kettle -v /home/vagrant/pentaho:/root/.pentaho hiromuhota/webspoon:latest-full
```

**Comment by diethardsteiner** [comment]
Thanks Hiromu for providing the solution. Yes, using the additional `z` makes it work in my case:

```
docker run -e JAVA_OPTS="-Xms1024m -Xmx2048m" -d -p 8080:8080 -p 9051:9051 -v kettle:/root/.kettle:z -v pentaho:/root/.pentaho:z hiromuhota/webspoon:latest-full
```

**Comment by HiromuHota** [comment]
For the record, `z` option changes the SELinux _label_. See [here](https://docs.docker.com/engine/admin/volumes/bind-mounts/#configure-the-selinux-label) for details.
For clarity, use the following example for bind mounts

```
docker run -e JAVA_OPTS="-Xms1024m -Xmx2048m" -d -p 8080:8080 -v /home/dsteiner/webspoon/kettle:/root/.kettle:z -v /home/dsteiner/webspoon/pentaho:/root/.pentaho:z hiromuhota/webspoon:latest-full
```

and use the following for (named) volumes

```
docker run -e JAVA_OPTS="-Xms1024m -Xmx2048m" -d -p 8080:8080 -v kettle:/root/.kettle -v pentaho:/root/.pentaho hiromuhota/webspoon:latest-full
```

Note that port 9051 mapping is no longer needed.
