### ISSUE TITLE
Notes can not be edited

### ISSUE THREAD

**Issue by mattcasters** [HiromuHota/webspoon-docker#15]
If you have a note in an existing transformation, you can't edit it.  You can't create notes either.
Below is the stack trace from spoon.log.  I think the color or font options are killing this one.

https://github.com/pentaho/pentaho-kettle/blob/8.1/ui/src/main/java/org/pentaho/di/ui/spoon/dialog/NotePadDialog.java

Looking at the stack trace I think it's an issue with putting images on buttons.
Line 361: wbFontColorChange.setImage( guiresource.getImageColor() );

2018-09-28 08:25:26,200 ERROR [org.pentaho.ui.xul.impl.AbstractXulDomContainer] Error invoking method: transgraph.editNote()
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:313)
        at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
        at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
        at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)
        at org.pentaho.ui.xul.jface.tags.JfaceMenuitem$1.run(JfaceMenuitem.java:106)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:493)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:575)
        at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:492)
        at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:403)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
        at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
        at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
        at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
        at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
        at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
        at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
        at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
        at java.lang.Thread.run(Thread.java:748)
        at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Caused by: java.lang.IllegalArgumentException: Argument not valid
        at org.eclipse.swt.SWT.error(SWT.java:3794)
        at org.eclipse.swt.SWT.error(SWT.java:3731)
        at org.eclipse.swt.SWT.error(SWT.java:3702)
        at org.eclipse.swt.widgets.Button.setImage(Button.java:304)
        at org.pentaho.di.ui.spoon.dialog.NotePadDialog.open(NotePadDialog.java:361)
        at org.pentaho.di.ui.spoon.trans.TransGraph.editNote(TransGraph.java:3441)
        at org.pentaho.di.ui.spoon.trans.TransGraph.editNote(TransGraph.java:2661)
        ... 25 more
2018-09-28 08:25:26,200 ERROR [org.pentaho.ui.xul.impl.AbstractXulComponent] Error calling oncommand event
org.pentaho.ui.xul.XulException: Error invoking method: transgraph.editNote()
        at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:317)
        at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:157)
        at org.pentaho.ui.xul.impl.AbstractXulComponent.invoke(AbstractXulComponent.java:141)
        at org.pentaho.ui.xul.jface.tags.JfaceMenuitem.access$100(JfaceMenuitem.java:43)
        at org.pentaho.ui.xul.jface.tags.JfaceMenuitem$1.run(JfaceMenuitem.java:106)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:493)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:575)
        at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:492)
        at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:403)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)
        at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)
        at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1217)
        at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1198)
        at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1181)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1173)
        at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)
        at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)
        at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)
        at java.lang.Thread.run(Thread.java:748)
        at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.pentaho.ui.xul.impl.AbstractXulDomContainer.invoke(AbstractXulDomContainer.java:313)
        ... 20 more
Caused by: java.lang.IllegalArgumentException: Argument not valid
        at org.eclipse.swt.SWT.error(SWT.java:3794)
        at org.eclipse.swt.SWT.error(SWT.java:3731)
        at org.eclipse.swt.SWT.error(SWT.java:3702)
        at org.eclipse.swt.widgets.Button.setImage(Button.java:304)
        at org.pentaho.di.ui.spoon.dialog.NotePadDialog.open(NotePadDialog.java:361)
        at org.pentaho.di.ui.spoon.trans.TransGraph.editNote(TransGraph.java:3441)
        at org.pentaho.di.ui.spoon.trans.TransGraph.editNote(TransGraph.java:2661)
        ... 25 more

**Comment by mattcasters** [comment]
Wrong project, sorry :-)
